# Site settings
title: s-flow's blog
description: programming study blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://s-flow.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: hyerim
user_description: developer
email: s.flow.origin@gmail.com
github_username:  s-flow.github.io


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
